### ISSUE TITLE
Black-holed

### ISSUE THREAD

**Issue by Setsuneh** [YunoHost-Apps/sonerezh_ynh#7]
Bonsoir,

Petit soucis sur mon nouveau ou j'ai installé Yunohost et notamment Sonerezh. J'ai tenté l'install en verbose, en vain ...

Une idée? Merci

```
The request has been black-holed
Error: The requested address '/sonerezh/login' was not found on this server.
```

**Comment by M5oul** [comment]
Tu rencontres ce problème de black-holed lorsque tu vas sur `/sonerezh/login` avec ton navigateur web ou lors de l’installation ?

Peux-tu fournir plus de détails sur ton problème.
Je ne comprends pas très bien.
L’application est fonctionnelle mais nécessite une post-installation manuelle.
