### ISSUE TITLE
Sonerezh 1.13

### ISSUE THREAD

**Issue by genma** [YunoHost-Apps/sonerezh_ynh#8]
sonerezh 1.1.3 was released and is aviable here : https://github.com/Sonerezh/sonerezh/archive/1.1.3.zip
I'll submit a merge request as soon as possible :)

**Comment by M5oul** [comment]
Thanks.
There is a tarball and it works.
I use it as it's already implemented.
zip is easier to implement. I could go back to zip later.
Currently, upgrade doesn't works. I have to investigate and rework the code.
